[Error] - 2018-10-16 15:59:03.475334 - a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "forkserver-v2.py", line 88, in handle_request
    request = self.recv_request(connection)
  File "forkserver-v2.py", line 149, in recv_request
    while self.HEADER_END_STRING not in data:
TypeError: a bytes-like object is required, not 'str'
[Error] - 2018-10-16 15:59:43.821758 - must be str, not bytes
Traceback (most recent call last):
  File "forkserver-v2.py", line 88, in handle_request
    request = self.recv_request(connection)
  File "forkserver-v2.py", line 154, in recv_request
    total_length = self.parse_headers(data)
  File "forkserver-v2.py", line 167, in parse_headers
    headers_length = data.find(self.HEADER_END_STRING) + len(self.HEADER_END_STRING)
TypeError: must be str, not bytes
[Error] - 2018-10-16 16:00:33.422270 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:04:31.280251 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:06:33.993531 - name 'HEADER_END_STRING' is not defined
Traceback (most recent call last):
  File "forkserver-v2.py", line 88, in handle_request
    request = self.recv_request(connection)
  File "forkserver-v2.py", line 156, in recv_request
    print(data.split(bytes(HEADER_END_STRING)))
NameError: name 'HEADER_END_STRING' is not defined
[Error] - 2018-10-16 16:06:47.709078 - string argument without an encoding
Traceback (most recent call last):
  File "forkserver-v2.py", line 88, in handle_request
    request = self.recv_request(connection)
  File "forkserver-v2.py", line 156, in recv_request
    print(data.split(bytes(self.HEADER_END_STRING)))
TypeError: string argument without an encoding
[Error] - 2018-10-16 16:07:39.432783 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:09:15.501287 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:10:18.262996 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:10:36.073608 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:14:14.520479 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:15:14.805375 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:15:31.156175 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:16:21.908739 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:21:27.637845 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:22:35.875649 - 
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(request)
  File "forkserver-v2.py", line 132, in parse_request
    assert isinstance(request, str)
AssertionError
[Error] - 2018-10-16 16:26:48.964429 - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "forkserver-v2.py", line 89, in handle_request
    self.parse_request(headers)
  File "forkserver-v2.py", line 132, in parse_request
    request = request.decode('UTF-8')
AttributeError: 'str' object has no attribute 'decode'
